# Logging
## default
logging.pattern.dateformat=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
logging.level.root=INFO
## custom
logging.level.com.pondit.portfolio=debug

# Database
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:./data/portfolio
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.show-sql=false

# Security
## TODO: don't push into git
security.rest.jwt.key=YzEyMzR0bXZxQzRmNTZ2cEFoUGVpMWdIajU3aWdoZ2g