INSERT INTO post (title, content, slug, is_published, published_at, intro) VALUES
                                                                               ('The Impact of Climate Change on Wildlife',
                                                                                'Climate change is profoundly affecting wildlife across the globe. Rising temperatures, shifting weather patterns, and altered habitats are forcing many species to adapt, migrate, or face the risk of extinction. Polar bears, coral reefs, and migratory birds are just a few examples of wildlife impacted by these environmental changes. Conservation efforts are increasingly focusing on mitigating these effects through habitat protection, climate action, and raising awareness about the interconnectedness of ecosystems. The survival of countless species depends on how effectively humanity addresses climate change in the coming decades.',
                                                                                'impact-of-climate-change-on-wildlife', TRUE, CURRENT_TIMESTAMP,
                                                                                'Examining how climate change is threatening wildlife and what can be done to protect vulnerable species.'),

                                                                               ('The Evolution of Digital Communication',
                                                                                'Digital communication has transformed how people connect, share ideas, and conduct business worldwide. From the invention of email and instant messaging to the rise of social media platforms, the way we communicate has become faster, more accessible, and often more visual. This evolution has bridged distances, enabling global collaboration and real-time interaction. However, it also presents challenges such as information overload, privacy concerns, and the spread of misinformation. Understanding the history and impact of digital communication is essential as society continues to navigate its benefits and pitfalls.',
                                                                                'the-evolution-of-digital-communication', TRUE, CURRENT_TIMESTAMP,
                                                                                'A comprehensive look at how digital communication has changed our world and the challenges it presents.');
