CREATE TABLE IF NOT EXISTS post (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    title VARCHAR(255),
                                    content CLOB,
                                    slug VARCHAR(255) NOT NULL UNIQUE,
                                    is_published BOOLEAN,
                                    published_at TIMESTAMP,
                                    intro VARCHAR(400)
);
CREATE TABLE IF NOT EXISTS project (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(255),
                                       description VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(255),
                                     password VARCHAR(255),
                                     firstName VARCHAR(255),
                                     lastName VARCHAR(255)
);
