CREATE TABLE IF NOT EXISTS post (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    title VARCHAR(255),
                                    content CLOB,
                                    slug VARCHAR(255) NOT NULL UNIQUE,
                                    is_published BOOLEAN,
                                    published_at TIMESTAMP,
                                    intro VARCHAR(400)
);
